server:
  port: 8000
spring:
  application:
    name: gateway-server
  profiles:
    active: local
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:5173"
              - "http://localhost:8000"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
            allowed-headers:
              - "*"
            allow-credentials: true
      httpclient:
        response-timeout: 5000
      routes:
        - id: commerce-server
          uri: lb://COMMERCE-SERVER
          predicates:
            - Path=/api/v1/s1/**
          filters:
            - RewritePath=/api/v1/s1/(?<segment>.*), /$\{segment}
#            - name: CircuitBreaker
#              args:
#                name: userServiceCB
#                failureRateThreshold: 70
#                minimumNumberOfCalls: 15
#                slidingWindowSize: 25
        - id: auth-server
          uri: lb://AUTH-SERVER
          predicates:
            - Path=/api/v1/s2/**
          filters:
            - RewritePath=/api/v1/s2/(?<segment>.*), /$\{segment}
        - id: commerce-swagger-server
          uri: lb://COMMERCE-SERVER
          predicates:
            - Path=/s1/v3/api-docs/**
        - id: auth-swagger-server
          uri: lb://AUTH-SERVER
          predicates:
            - Path=/s2/v3/api-docs/**
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka



#logging:
#  level:
#    org.springframework.cloud.gateway: trace
#    reactor.netty: trace